openapi: 3.0.3
info:
  title: 항해플러스 e-commerce API
  version: 1.0.11
servers:
  - url: http://localhost:8080
tags:
  - name: user
    description: 사용자에 관한 작업을 제공합니다.
  - name: product
    description: 상품에 관한 작업을 제공합니다.
  - name: coupon
    description: 쿠폰에 관한 작업을 제공합니다.
  - name: order
    description: 주문에 관한 작업을 제공합니다.
  - name: payment
    description: 결제에 관한 작업을 제공합니다.
paths:
  /api/v1/user/balance/{userId}:
    get:
      tags:
        - user
      summary: 잔액 조회 요청
      operationId: getBalance
      parameters:
        - name: userId
          in: path
          required: true
          description: 사용자 ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 잔액 조회 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
  /api/v1/user/balance/charge:
    post:
      tags:
        - user
      summary: 잔액 충전 요청
      operationId: chargeBalance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChargeBalanceRequest'
      responses:
        '200':
          description: 잔액 충전 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
  /api/v1/user/coupons/{userId}:
    get:
      tags:
        - user
      summary: 보유 쿠폰 조회 요청
      operationId: getUserCoupons
      parameters:
        - name: userId
          in: path
          required: true
          description: 사용자 ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 보유 쿠폰 조회 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCouponsResponse'  
                
  /api/v1/product:
    get:
      tags:
        - product
      summary: 상품 목록 조회 요청
      operationId: getProducts
      responses:
        '200':
          description: 상품 목록 조회 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
  /api/v1/product/popular:
    get:
      tags:
        - product
      summary: 인기 상품 목록 조회 요청
      operationId: getPopularProducts
      responses:
        '200':
          description: 인기 상품 목록 조회 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
  /api/v1/coupon/issue:
    post:
      tags:
        - coupon
      summary: 쿠폰 발급 요청
      operationId: issueCoupon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CouponRequest'
      responses:
        '200':
          description: 쿠폰 발급 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponResponse'
  /api/v1/order:
    post:
      tags:
        - order
      summary: 주문 요청
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '200':
          description: 주문 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
  /api/v1/payment:
    post:
      tags:
        - payment
      summary: 결제 요청
      operationId: createPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        '200':
          description: 결제 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'                      
components:
  schemas:
    BalanceResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        balance:
          type: number
          format: double
      required:
        - userId
        - balance
    ChargeBalanceRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          description: 사용자 ID
        amount:
          type: integer
          description: 충전 금액
      required:
        - userId
        - amount
    UserCouponsResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          description: 사용자 ID
        userCoupons:
          type: array
          items:
            $ref: '#/components/schemas/UserCouponInfo'
      required:
        - userId
        - userCoupons
    UserCouponInfo:
      type: object
      properties:
        couponId:
          type: integer
          format: int64
          description: 쿠폰 ID
        name:
          type: string
          description: 쿠폰 이름
        amount:
          type: number
          format: decimal
          description: 쿠폰 금액
        validStartDate:
          type: string
          format: date-time
          description: 쿠폰 유효 시작 날짜
        validEndDate:
          type: string
          format: date-time
          description: 쿠폰 유효 종료 날짜
        status:
          type: string
          enum:
            - UNUSED
            - USED
          description: 쿠폰 상태
      required:
        - couponId
        - name
        - amount
        - validStartDate
        - validEndDate
        - status
    UserCouponStatus:
      type: string
      enum:
        - UNUSED
        - USED
    ProductsResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductInfo'
      required:
        - products
    ProductInfo:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: 제품 ID
        name:
          type: string
          description: 제품 이름
        price:
          type: integer
          description: 제품 가격
      required:
        - productId
        - name
        - price
    CouponRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        couponId:
          type: integer
          format: int64
      required:
        - userId
        - couponId
    CouponResponse:
      type: object
      properties:
        couponId:
          type: integer
          format: int64
          description: 쿠폰 ID
        name:
          type: string
          description: 쿠폰명
        amount:
          type: number
          format: decimal
          description: 쿠폰 금액
        validStartDate:
          type: string
          format: date-time
          description: 쿠폰 유효 시작 날짜
        validEndDate:
          type: string
          format: date-time
          description: 쿠폰 유효 종료 날짜
      required:
        - couponId
        - name
        - amount
        - validStartDate
        - validEndDate    
    CreateOrderRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        couponId:
          type: integer
          format: int64
        products:
          type: array
          items:
            $ref: '#/components/schemas/OrderProductInfo'
      required:
        - userId
        - products
    OrderResponse:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
          description: 주문 ID
        totalAmount:
          type: number
          format: decimal
          description: 총 주문 금액
        discountAmount:
          type: number
          format: decimal
          description: 할인 금액
        paymentAmount:
          type: number
          format: decimal
          description: 결제 금액
        createdAt:
          type: string
          format: date-time
          description: 주문 생성 날짜 및 시간
      required:
        - orderId
        - totalAmount
        - paymentAmount
        - createdAt
    CreatePaymentRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
      required:
        - userId
        - orderId      
    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: integer
          format: int64
          description: 결제 ID
        totalAmount:
          type: number
          format: double
          description: 총 금액
        discountAmount:
          type: number
          format: double
          description: 할인 금액
        paymentAmount:
          type: number
          format: double
          description: 결제 금액
      required:
        - paymentId
        - totalAmount
        - discountAmount
        - paymentAmount
    OrderProductInfo:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
      required:
        - productId
        - quantity
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header